---
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - apt-transport-https
    - ca-certificates
  tags: install

- name: Add apt key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.2.asc
    state: present
  tags: install

- name: Add mongo repository
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse
    state: present
  tags: install

- name: Install mongodb
  apt:
    name: mongodb-org
    state: present
  tags: install

- name: Start mongodb service
  systemd:
    name: mongod
    state: started
    enabled: yes
  tags: install
